import type { Metadata } from "next";
import { Space_Grotesk, Spectral } from "next/font/google";

import { Provider } from "@/components/ui/provider";
import "./globals.css";
import styles from "./page.module.css";
import { Analytics } from "@vercel/analytics/next";

import Script from "next/script";

const SpectralFont = Spectral({
  // For Headings
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-spectral",
});

const SpaceGrotesk = Space_Grotesk({
  // For Body
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes={"192x192"} />
        <Script
          type="text/javascript"
          src="/platforms/load.js"
          strategy="afterInteractive"
        ></Script>
        <script
          async
          id="cookieyes"
          type="text/javascript"
          src="https://cdn-cookieyes.com/client_data/5cd9002534c83870252a4773/script.js"
        ></script>
        <script
          async
          src="https://js.sentry-cdn.com/17dc7fee29c01933e3c3df799f1c804b.min.js"
        ></script>
      </head>
      <body
        className={`${SpectralFont.variable} ${SpaceGrotesk.variable} ${styles.body}`}
      >
        <Provider>
          {children}
          <Analytics />
        </Provider>
      </body>
    </html>
  );
}
